<a href="https://colab.research.google.com/github/dudgus1286/pandas/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 넘파이
- 과학 계산 및 수학 계산
- 이미지와 컴퓨터 그래픽을 빠르게 처리
- 반복문 작성하지 않고 전체 데이터 배열을 빠르게 계산할 수 있는 수학 함수 제공

> 넘파이 배열
- 벡터(1차원)와 매트리스(2차원)를 배열이라고 함
- 머신러닝에서 사용하는 주요 데이터 구조

In [2]:
import numpy as np

### 1. 1차원 배열(벡터)

In [ ]:
array1 = np.array([1,2,3,4])

In [ ]:
array1.shape

(4,)

### 2. 2차원 배열)매트릭스

In [ ]:
data1 = [
    [1,2,3],
    [4,5,6]
]

array2 = np.array(data1)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array2.shape

(2, 3)

In [ ]:
array3 = np.array([[1,2,3,4]])
array3.shape

(1, 4)

In [ ]:
# ndim : 차원 수 알아보기

print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
2


In [ ]:
# 파이썬에서 리스트는 서로 다른 타입 가질 수 있음

list1 = [1,2,"a",3.5]
list1

[1, 2, 'a', 3.5]

In [ ]:
# numpy 는 하나의 타입으로 변경해서 array 생성

np.array(list1)
# array(['1', '2', 'a', '3.5'], dtype='<U32')

array(['1', '2', 'a', '3.5'], dtype='<U32')

In [ ]:
# array1.dtype
# astype()

# float64 : float 를 64 비트로 표현
array_f1 = array1.astype("float64")
array_f1
array_f1.dtype

dtype('float64')

### 3. 넘파이 함수

In [ ]:
# arange(n) : 0 ~ n -1 에 해당하는 넘파이 배열 생성

np.arange(10)
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.arange(5,10)
# array([5, 6, 7, 8, 9])

np.arange(1,10,2)
# array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [ ]:
# 1 ~ 100 까지 5의 배수 넘파이 배열 생성
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [ ]:
# zeros(n) : n 개 만큼 0을 채워서 넘파이 1차원 배열 생성
# zeros(행, 열) : 2차원 배열

np.zeros(4)

np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
# ones(n) : n 개 만큼 1을 채워서 넘파이 1차원 배열 생성
np.ones(4)

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# np.empty() : 임의의 값을 넣어줌

np.empty(4)
np.empty((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# np.full() : 특정한 값으로 채워진 넘파이 배열 생성

# np.full(4) 오류 남
np.full(4, fill_value=7)
np.full((2,4), fill_value=5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
# np.eye(n) : 단위행렬

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# np.linsplace(시작, 끝, 전체개수) : 시작과 끝 사이 정해진 개수만큼의 균등하게 분열된 값으로 반환

np.linspace(1,10, 5)
np.linspace(1,10, 4)

array([ 1.,  4.,  7., 10.])

In [ ]:
# np.random.rand(n) : 0 ~ 1 사이의 숫자를 랜덤하게 n 개의 배열에 담아서 반환

np.random.rand(2,3)

array([[0.387851  , 0.35340309, 0.93854847],
       [0.95366305, 0.19312272, 0.38005406]])

In [ ]:
# np.random.randn() : 정규분포로 샘플링된 배열 생성

# np.random.randn()
# np.random.randn(5)
np.random.randn(3,4)

array([[-1.79988491, -0.80143197,  0.39547324,  2.22903663],
       [-0.18882173, -1.10013795, -1.35838501,  0.3428448 ],
       [ 1.28180357, -0.80834871, -0.91186599, -0.99396842]])

In [ ]:
# np.random.randint(시작, 마지막, 개수) : 특정 범위 안의 숫자 출력

np.random.randint(1,10,5)

array([1, 3, 3, 8, 2])

In [53]:
# np.random.seed(임의의 숫자) : random 사용 시 실행할 때마다 결과가 다르게 나오는 것을 방지

np.random.seed(140)
np.random.randn(2,3)

array([[-0.46716782,  0.29599552,  0.18548011],
       [-0.82809842, -0.03192753,  1.00155352]])

In [ ]:
# np.random.choice(n) : 0 ~ n 까지 임의의 수 추출

np.random.choice(100)
np.random.choice(100, size=(3,4))

array([[47, 66, 75,  5],
       [36, 36, 40, 13],
       [84, 33, 67, 20]])

### 4. 인덱싱과 슬라이싱

In [6]:
# 인덱싱
arr1 = np.arange(1,10)
arr1

print(arr1[2])
print(arr1[-2])

arr1[3] = 18
arr1

3
8


array([ 1,  2,  3, 18,  5,  6,  7,  8,  9])

In [12]:
# reshape()

# 1차원 배열을 2차원 배열로 재구성
arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
print(arr1[0,0])
print(arr1[1,1])

1
5


In [15]:
# 3차원 : 텐서

arr1 = np.arange(36).reshape(3,4,3)
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [16]:
arr1[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
arr1[0,1]

array([3, 4, 5])

In [20]:
arr1[0,1,-1]

5

In [21]:
# 16 출력

arr1[1,1,1]

16

In [23]:
# 슬라이싱
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr1[0:3]
arr1[:3]
arr1[3:]

array([4, 5, 6, 7, 8, 9])

In [27]:
arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
# 1과 4 출력

arr1[:2,:1]

array([[1],
       [4]])

In [32]:
arr1[1:3, :]

array([[4, 5, 6],
       [7, 8, 9]])

In [33]:
arr1[arr1>5]

array([6, 7, 8, 9])

### 데이터 형태 변경

In [34]:
y = np.arange(15).reshape(3,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
# 2차원 이상의 배열을 1차원으로 변환

y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
# 2행 3열

x = np.arange(30).reshape(2,3,5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [41]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### ndarray 기본 함수
- add(), subtract(), multiply(), divide() 기본함수 제공

In [42]:
x = np.array([[4,4,4],[8,8,8]])
y = np.array([[1,1,1],[2,2,2]])

In [43]:
x + y

array([[ 5,  5,  5],
       [10, 10, 10]])

In [44]:
x - y

array([[3, 3, 3],
       [6, 6, 6]])

In [45]:
x * y

array([[ 4,  4,  4],
       [16, 16, 16]])

In [46]:
x / y

array([[4., 4., 4.],
       [4., 4., 4.]])

In [47]:
np.add(x,y)

array([[ 5,  5,  5],
       [10, 10, 10]])

In [48]:
np.subtract(x,y)

array([[3, 3, 3],
       [6, 6, 6]])

In [49]:
np.multiply(x,y)

array([[ 4,  4,  4],
       [16, 16, 16]])

In [50]:
np.divide(x,y)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [54]:
x = np.random.rand(15)
x

array([0.27527877, 0.10268944, 0.09207659, 0.85574278, 0.7547835 ,
       0.36064195, 0.03971011, 0.88210098, 0.50737996, 0.73691749,
       0.8361513 , 0.15280743, 0.50877979, 0.90080608, 0.25138757])

In [55]:
# 평균
x.mean()

0.48381691774292096

In [56]:
# 최대값의 인덱스 번호를 반환
x.argmax()

13

In [57]:
# 표준편차
x.std()

0.3111098489711636

In [58]:
x.sum()

7.257253766143815

In [59]:
# 이전 요소와 순차적으로 덧셈합
x.cumsum()

array([0.27527877, 0.37796821, 0.4700448 , 1.32578758, 2.08057109,
       2.44121304, 2.48092316, 3.36302413, 3.87040409, 4.60732159,
       5.44347289, 5.59628032, 6.10506012, 7.00586619, 7.25725377])